package Skeleton;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Entity.java
//  @ Date : 2021. 03. 19.
//  @ Author : 
//
//




public abstract class Entity {
	protected Thing location;
	public void drill() {
	}
	
	public void move(Thing destination) {
	}
	
	public void wait() {

	}
	
	public abstract void die();
	
	public abstract void explode();
}
