//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Material.java
//  @ Date : 2021. 03. 19.
//  @ Author : 
//
//




public class Material {
	private Asteroid myAsteroid;
	public void nearSun() {
	}
}
