//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Robot.java
//  @ Date : 2021. 03. 19.
//  @ Author : 
//
//




public class Robot extends Entity {
	private SolarSystem mySystem;
	public void die() {
	}
	
	public void explode() {
	}
	
	public void die() {
	}
	
	public void explode() {
	}
}
