//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SolarSystem.java
//  @ Date : 2021. 03. 19.
//  @ Author : 
//
//

package Skeleton;


public class SolarSystem {
	private Robot robots;
	private Settler settlers;
	private Thing things;
	public void win() {
	}
	
	public void lose() {
	}
	
	public void removeThing(Thing t) {
	}
	
	public void addThing(Thing t) {
	}
	
	public void removeRobot(Robot r) {
	}
	
	public void addRobot(Robot r) {
	}
	
	public void removeSettler(Settler s) {
	}
	
	public void makeSolarEruption() {
	}
	
	public void startGame() {
	}
}
