//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TeleportGate.java
//  @ Date : 2021. 03. 19.
//  @ Author : 
//
//




public class TeleportGate extends Thing {
	public Settler Unnamed1;
	private TeleportGate pair;
	public void applySunEruption() {
	}
	
	public void activate() {
	}
}
