//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Uran.java
//  @ Date : 2021. 03. 19.
//  @ Author : 
//
//




public class Uran extends Material {
	public void nearSun() {
	}
}
