//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Asteroid.java
//  @ Date : 2021. 03. 19.
//  @ Author : 
//
//


public class Asteroid extends Thing {
	private int layer;
	private boolean nearBySun;
	protected Material core;
	public void explode() {
	}
	
	public Material excavate() {
	}
	
	public void placeMaterial(Material m) {
	}
	
	public void drill() {
	}
	
	public void applySunEruption() {
	}
	
	public void buildBase(Material m) {
	}
}
