//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MainAsteroid.java
//  @ Date : 2021. 03. 19.
//  @ Author : 
//
//




public class MainAsteroid extends Asteroid {
	private Material builtIn;
	public void buildBase(Material m) {
	}
}
