//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Settler.java
//  @ Date : 2021. 03. 19.
//  @ Author : 
//
//




public class Settler extends Entity {
	private TeleportGate gates;
	private SolarSystem mySystem;
	private Material materials;
	public void mine() {
	}
	
	public void buildBase() {
	}
	
	public void buildGate() {
	}
	
	public void buildRobot() {
	}
	
	public void placeMaterial(Material m) {
	}
	
	public void putGateDown(TeleportGate g) {
	}
	
	public void addGate(TeleportGate g) {
	}
	
	public void addMaterial(Material m) {
	}
	
	public void rmMaterial(Material m) {
	}
	
	public void die() {
	}
	
	public void explode() {
	}
	
	public void die() {
	}
	
	public void explode() {
	}
}
