//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Silicon.java
//  @ Date : 2021. 03. 19.
//  @ Author : 
//
//




public class Silicon extends Material {
}
